# Generated by Django 5.2 on 2025-06-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='alt_mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='mobile_number',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
    ]
